# some digimon have modes that don't have " Mode" in the name
known_mode_variants = [
    "apollomon_whispered",
    "fenriloogamon_takemikazuchi",
    "sistermon_ciel_Awake",
    "sistermon_noir_Awake",
    "sistermon_blanc_Awake",
    "blacktailmon_uver",
    "omegamonzwart_d",
    "jesmongx",
    "shoutmon_king",
    "aegiochusmon:blue",
    "aegiochusmon:dark",
    "aegiochusmon:green",
    "aegiochusmon_holly",
    "agnimon",
    "vritramon",
    "terriermon_assistant",
    "wolfmon",
    "garummon",
    "ranamon",
    "calamaramon",
    "fairimon",
    "shutumon",
    "blitzmon",
    "bolgmon",
    "duskmon",
    "velgrmon",
    "louwemon",
    "kaiserleomon",
    "chackmon",
    "blizzarmon",
    "zombieplutomon",
    "arbormon",
    "petaldramon",
    "gigasmon",
    "grottemon",
    "mercuremon",
    "sephirothmon",
    "omegamon_alter-b",
    "omegamon-alter-s",
    "metalgreymon_cyberlauncher",
    "ginkakumon_promote"
]

# map digimon to their modes. note that these are not always
# semantically bidirectional.
digimon_modes = {
    "apollomon": ["apollomon_whispered"],
    "armamon": ["armamon_burstmode"],
    "chronomon_destroy": ["chronomon_holy"],
    "chronomon_holy": ["chronomon_destroy"],
    "nezhamon": ["nazhamon_crimson"],
    "takutoumon": ["takutoumon_wrath"],
    "fenriloogamon": ["fenriloogamon_takemikazuchi"],
    "huanglongmon": ["huanglongmon_ruin"],
    "shinegreymon": ["shinegreymonburstmode", "shinegreymon_ruin"],
    "imperialdramonfightermode_vi": ["imperialdramon_dragon_black"],
    "imperialdramon_dragon_black": ["imperialdramonfightermode_vi"],
    "imperialdramonfightermode": ["imperialdramondragonmode"],
    "imperialdramondragonmode": ["imperialdramonfightermode"],
    "jupitermon": ["jupitermmon_wrath"],
    "sistermon_ciel": ["sistermon_ciel_Awake"],
    "sistermonnoir": ["sistermon_noir_Awake"],
    "sistermonblanc": ["sistermon_blanc_Awake"],
    "blacktailmon": ["blacktailmon_uver"],
    "omegamon_zwart": ["omegamonzwart_d", "omegamon"],
    "omegamonzwart_d": ["omegamon_alter-b"],
    "omegamon_alter-b": ["omegamonzwart_d", "omegamon-alter-s"],
    "omegamon-alter-s": ["omegamon_alter-b"],
    "omegamon": ["omegamon_zwart"],
    "shoutmonx7": ["shoutmonx7_superior"],
    "weregarrumon": ["waregarurumon_sagittarius"],
    "metalgreymon-v": ["metalgreymon_alter"],
    "metalgreymon": ["metalgreymon_alter", "metalgreymon_cyberlauncher"],
    "eyesmon": ["eyesmon_scatter"],
    "arresterdramon": ["arresterdramon_superior"],
    "jesmon": ["jesmongx"],
    "rasenmon": ["rasenmon_f"],
    "ofanimon_x": ["ofanimonfdm_x"],
    "ofanimon": ["ofanimonfalldownmode"],
    "justimon": ["justimon_blitzarm", "justimon_criticalarm"],
    "justimon_blitzarm": ["justimon", "justimon_criticalarm"],
    "justimon_criticalarm": ["justimon_blitzarm", "justimon"],
    "kuzuhamon": ["kuzuhamon_miko"],
    "cerberumon": ["cerberumon_werewolfmode"],
    "cerberumon_werewolfmode": ["cerberumon"],
    "aegiochusmon": ["aegiochusmon:blue", "aegiochusmon:dark", "aegiochusmon:green", "aegiochusmon_holly"],
    "madleomon": ["madleomon:armedmode"],
    "meicrackmon": ["meicrackmon_v"],
    "skullknightmon": ["skullknightmonbigaxemode", "skullknightmoncavaliermode"],
    "rosemon": ["rosemonburstmode"],
    "ravmon": ["ravmonburstmode"],
    "lucemonlarva": ["lucemonsatanmode"],
    "lucemonsatanmode": ["lucemonlarva"],
    "miragegaogamon": ["miragegaogamon:burstmode"],
    "belphemonsleepmode": ["belphemonragemode"],
    "belphemonragemode": ["belphemonsleepmode"],
    "beelzebumon": ["beelzebumonblastmode"],
    "duftmon": ["duftmonleopardmode"],
    "duftmonleopardmode": ["duftmon"],
    "dukemon": ["dukemoncrimsonmode"],
    "sakuyamon": ["sakuyamon:mikomode"],
    "agnimon": ["vritramon"],
    "vritramon": ["agnimon"],
    "terriermon": ["terriermon_assistant"],
    "terriermon_assistant": ["terriermon"],
    "wolfmon": ["garummon"],
    "garummon": ["wolfmon"],
    "ranamon": ["calamaramon"],
    "calamaramon": ["ranamon"],
    "blitzmon": ["bolgmon"],
    "bolgmon": ["blitzmon"],
    "fairimon": ["shutumon"],
    "shutumon": ["fairimon"],
    "duskmon": ["velgrmon"],
    "velgrmon": ["duskmon"],
    "louwemon": ["kaiserleomon"],
    "kaiserleomon": ["louwemon"],
    "chackmon": ["blizzarmon"],
    "blizzarmon": ["chackmon"],
    "plutomon": ["zombieplutomon"],
    "zombieplutomon": ["plutomon"],
    "petaldramon": ["arbormon"],
    "arbormon": ["petaldramon"],
    "grottemon": ["gigasmon"],
    "gigasmon": ["grottemon"],
    "mercuremon": ["sephirothmon"],
    "sephirothmon": ["mercuremon"],
    "junomon": ["junomon_hysteric"],
    "erlangmon": ["erlangmon_blast"],
    "gaioumon": ["gaioumon_itto"],
    "ginkakumon": ["ginkakumon_promote"],
    "kinkakumon": ["ginkakumon_promote"]
}
